version: '3'

services:
  dicecat:
    restart: unless-stopped
    container_name: dicecat 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config

# vim: tabstop=2 shiftwidth=2 expandtab
